from __future__ import annotations

from datetime import UTC, datetime

from pypproxy.store.models import Entry


def generate_html(
    entries: list[Entry],
    title: str = "pypproxy Report",
    scan_results: list[dict] | None = None,
    security_results: list[dict] | None = None,
) -> str:
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    hosts = sorted({e.host for e in entries if e.host})
    status_counts: dict[str, int] = {}
    for e in entries:
        if e.status_code:
            bucket = f"{e.status_code // 100}xx"
            status_counts[bucket] = status_counts.get(bucket, 0) + 1

    findings = (scan_results or []) + (security_results or [])
    vulns = [f for f in findings if f.get("vulnerable") or f.get("suspicious")]

    rows = []
    for e in entries[:500]:
        ct = e.resp_headers.get("content-type", [""])[0][:40]
        rows.append(f"""
        <tr class="{"err" if e.status_code >= 400 else ""}">
          <td>{e.id}</td>
          <td><span class="badge m-{e.method.lower()}">{e.method}</span></td>
          <td class="mono">{e.host}{e.path[:60]}</td>
          <td><span class="badge s-{e.status_code // 100}">{e.status_code or "—"}</span></td>
          <td>{e.duration_ms or "—"} ms</td>
          <td>{len(e.resp_body):,} B</td>
          <td class="ct">{ct}</td>
        </tr>""")

    vuln_rows = []
    for f in vulns:
        vuln_rows.append(f"""
        <tr>
          <td><span class="badge s-4">{f.get("check", f.get("category", ""))}</span></td>
          <td class="mono">{f.get("param", f.get("url", ""))}</td>
          <td>{f.get("detail", f.get("description", ""))}</td>
          <td class="mono">{str(f.get("evidence", f.get("reason", "")))[:100]}</td>
        </tr>""")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0d1117; color: #c9d1d9; margin: 0; padding: 20px; }}
  h1, h2, h3 {{ color: #e6edf3; }}
  .summary {{ display: flex; gap: 16px; flex-wrap: wrap; margin: 16px 0; }}
  .card {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 16px 24px; min-width: 140px; }}
  .card .num {{ font-size: 2rem; font-weight: bold; color: #58a6ff; }}
  .card .label {{ font-size: 0.8rem; color: #8b949e; }}
  table {{ width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 13px; }}
  th {{ background: #21262d; color: #8b949e; padding: 8px 12px; text-align: left; border-bottom: 1px solid #30363d; }}
  td {{ padding: 6px 12px; border-bottom: 1px solid #21262d; }}
  tr:hover td {{ background: #1f2937; }}
  tr.err td {{ background: #2d1515; }}
  .mono {{ font-family: 'SF Mono', Consolas, monospace; font-size: 12px; }}
  .ct {{ font-size: 11px; color: #8b949e; }}
  .badge {{ display: inline-block; padding: 2px 6px; border-radius: 4px; font-size: 11px; font-weight: bold; }}
  .m-get {{ background: #0d419d; color: #79c0ff; }}
  .m-post {{ background: #1a4d1a; color: #56d364; }}
  .m-put {{ background: #4d3800; color: #e3b341; }}
  .m-delete {{ background: #4d1515; color: #f85149; }}
  .m-patch {{ background: #2d1a4d; color: #d2a8ff; }}
  .s-2 {{ background: #1a4d1a; color: #56d364; }}
  .s-3 {{ background: #0d419d; color: #79c0ff; }}
  .s-4 {{ background: #4d3800; color: #e3b341; }}
  .s-5 {{ background: #4d1515; color: #f85149; }}
  .vuln {{ background: #4d1515; border: 1px solid #f85149; border-radius: 8px; padding: 12px; margin: 8px 0; }}
  footer {{ margin-top: 32px; color: #8b949e; font-size: 12px; text-align: center; }}
</style>
</head>
<body>
<h1>{title}</h1>
<p style="color:#8b949e">Generated {now} &nbsp;·&nbsp; pypproxy</p>

<h2>Summary</h2>
<div class="summary">
  <div class="card"><div class="num">{len(entries)}</div><div class="label">Total Requests</div></div>
  <div class="card"><div class="num">{len(hosts)}</div><div class="label">Hosts</div></div>
  {"".join(f'<div class="card"><div class="num">{v}</div><div class="label">{k}</div></div>' for k, v in sorted(status_counts.items()))}
  <div class="card"><div class="num" style="color:#f85149">{len(vulns)}</div><div class="label">Findings</div></div>
</div>

{"<h2>Findings</h2><table><tr><th>Check</th><th>Target</th><th>Detail</th><th>Evidence</th></tr>" + "".join(vuln_rows) + "</table>" if vulns else ""}

<h2>Traffic ({len(entries)} requests)</h2>
<table>
  <tr><th>#</th><th>Method</th><th>Host + Path</th><th>Status</th><th>Time</th><th>Size</th><th>Content-Type</th></tr>
  {"".join(rows)}
</table>

<footer>Generated by <a href="https://github.com/ykus4/pypproxy" style="color:#58a6ff">pypproxy</a></footer>
</body>
</html>"""


def generate_markdown(
    entries: list[Entry],
    title: str = "pypproxy Report",
    scan_results: list[dict] | None = None,
    security_results: list[dict] | None = None,
) -> str:
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    hosts = sorted({e.host for e in entries if e.host})
    findings = (scan_results or []) + (security_results or [])
    vulns = [f for f in findings if f.get("vulnerable") or f.get("suspicious")]

    lines = [
        f"# {title}",
        "",
        f"Generated: {now}  ",
        f"Total requests: **{len(entries)}** | Hosts: **{len(hosts)}** | Findings: **{len(vulns)}**",
        "",
    ]

    if vulns:
        lines += ["## Findings", ""]
        lines += ["| Check | Target | Detail |", "|-------|--------|--------|"]
        for f in vulns:
            check = f.get("check", f.get("category", ""))
            target = f.get("param", f.get("url", ""))
            detail = f.get("detail", f.get("description", ""))
            lines.append(f"| {check} | `{target}` | {detail} |")
        lines.append("")

    lines += ["## Traffic", ""]
    lines += [
        "| # | Method | Host + Path | Status | ms | Size |",
        "|---|--------|-------------|--------|----|------|",
    ]
    for e in entries[:200]:
        path = (e.host + e.path)[:60]
        lines.append(
            f"| {e.id} | {e.method} | `{path}` | {e.status_code or '—'} | {e.duration_ms or '—'} | {len(e.resp_body):,} B |"
        )

    lines += ["", "---", "*Generated by [pypproxy](https://github.com/ykus4/pypproxy)*"]
    return "\n".join(lines)
